### ISSUE TITLE
"flash_attn" were not found in your environment

### ISSUE THREAD

**Issue by czhhzc** [baaivision/Emu3#21]
When I try to run the example code, it raise the below problem even if I have installed the "flash_attn" package.
```
Traceback (most recent call last):
  File "/home/zhcheng/projects/Emu3/function_test.py", line 14, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/zhcheng/.conda/envs/Emu3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/zhcheng/.conda/envs/Emu3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/zhcheng/.conda/envs/Emu3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/zhcheng/.conda/envs/Emu3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run 'pip install flash_attn'
```

**Comment by ryanzhangfan** [comment]
Please make sure you have installed flash-attn correctly as specified in requirements.txt. Try running `pip install flash-attn==2.5.7` or follow the [official installation guidance](https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features).

**Comment by bighuang624** [comment]
@czhhzc Similar issue. Fixed with https://github.com/Dao-AILab/flash-attention/issues/966#issuecomment-2406753469
